name: Build & Publish Feeds

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"  # 每天 4 次（UTC）
  workflow_dispatch:

# 部署 GitHub Pages 需要的权限（不需要写代码仓库）
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build feeds
        run: |
          python scripts/build_feeds.py

      # 直接把当前目录打包为 Pages 制品（包含生成的 feeds/*.xml）
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: feeds

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
