name: Build & Publish Feeds

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"  # 每天 4 次（UTC）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build feeds
        run: |
          python scripts/build_feeds.py

      - name: Commit feeds
        run: |
          git config user.name "feed-bot"
          git config user.email "feed-bot@users.noreply.github.com"
          git add feeds/*.xml || true
          git commit -m "update feeds" || echo "no changes"
          git push

  pages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - uses: actions/deploy-pages@v4
